source 'https://rubygems.org'

gem "jekyll", "~> 4.3.3" # installed by `gem jekyll`
gem "jekyll-remote-theme" # required for the remote theme
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.7.0" # pinned to the current release
# gem "just-the-docs"        # always download the latest release
